name: Build and Deploy to ECS via CodePipeline

on:
  push:
    branches:
      - main 

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Allows cloning repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # Configure AWS credentials via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push Docker image using docker/build-push-action
      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: .                          
          file: ./Dockerfile                  
          push: true
          tags: ${{ secrets.ECR_REPOSITORY_URI }}:latest

      # Trigger CodePipeline
      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name ${{ secrets.CODEPIPELINE_NAME }}
