name: Build and Deploy to ECS via CodePipeline (Blue/Green)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout source
        uses: actions/checkout@v4

      # 2. Configure AWS credentials (OIDC)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      # 3. Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image with commit SHA
      - name: Build and Push Docker image
        run: |
          ECR_REPO_URI=${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          docker push $ECR_REPO_URI:$IMAGE_TAG

      # 5. Render ECS task definition with new image URI
      - name: Generate ECS task definition
        run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}
          CONTAINER_NAME=${{ secrets.ECS_CONTAINER_NAME }}

          jq --arg image "$IMAGE_URI" --arg name "$CONTAINER_NAME" \
            '.containerDefinitions[0].image=$image | .containerDefinitions[0].name=$name' \
            taskdef.json > taskdef-rendered.json

      # 6. Create AppSpec file and ZIP deployment artifact
      - name: Prepare deployment artifact
        run: |
          CONTAINER_NAME=${{ secrets.ECS_CONTAINER_NAME }}

          cat > appspec.yml <<EOF
          version: 0.0
          Resources:
            - TargetService:
                Type: AWS::ECS::Service
                Properties:
                  TaskDefinition: "arn:aws:ecs:eu-central-1:004165097941:task-definition/ecs-lab-task:14"
                  LoadBalancerInfo:
                    ContainerName: "$CONTAINER_NAME"
                    ContainerPort: 8080
          EOF

          # Print for debugging
          echo "==== AppSpec.yml ===="
          cat appspec.yml
          echo "==== Task Definition ===="
          cat taskdef-rendered.json

          # Create zip file
          zip deployment-artifact.zip appspec.yml taskdef-rendered.json

          # List contents
          unzip -l deployment-artifact.zip

      # 7. Upload artifact to S3 using the correct key
      - name: Upload to S3
        run: |
          aws s3 cp deployment-artifact.zip s3://${{ secrets.ARTIFACT_BUCKET }}/appspec-artifact.zip

      # 8. Trigger CodePipeline
      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name ${{ secrets.CODEPIPELINE_NAME }}
