name: Build and Deploy to ECS via CodePipeline

on:
  push:
    branches:
      - main   # change if your branch is different

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Configure AWS credentials via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Build and Push Docker image
      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=latest
          ECR_REPO_URI=${{ secrets.ECR_REPOSITORY_URI }}
          echo "Building Docker image..."
          docker build -t $ECR_REPO_URI:$IMAGE_TAG .
          echo "Pushing to ECR..."
          docker push $ECR_REPO_URI:$IMAGE_TAG

      # Create imagedefinitions.json for ECS deployment
      - name: Create imagedefinitions.json
        run: |
          cat > imagedefinitions.json <<EOL
          [
            {
              "name": "${{ secrets.ECS_CONTAINER_NAME }}",
              "imageUri": "${{ secrets.ECR_REPOSITORY_URI }}:latest"
            }
          ]
          EOL
          cat imagedefinitions.json

      # Upload imagedefinitions.json to CodePipeline artifact bucket
      - name: Upload imagedefinitions.json to S3
        run: |
          aws s3 cp imagedefinitions.json s3://${{ secrets.ARTIFACT_BUCKET }}/imagedefinitions.json

      # Trigger CodePipeline to start ECS deployment
      - name: Trigger CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name ${{ secrets.CODEPIPELINE_NAME }}
